// export const healthPackages = [
//   {
//     category: "popular",
//     items: [
//       {
//         availableAt: "Home",
//         category: "popular",
//         couponCode: "LABS10",
//         discount: "52% OFF",
//         discountedPrice: 1099,
//         fasting: "10 - 12 Hrs",
//         id: 1,
//         is80DEligible: true,
//         offer: "Hurry! Flat 5% Off",
//         originalPrice: 2299,
//         reportsTime: "24 - 48 Hrs",
//         tests: [
//           "Complete Blood Count (CBC)",
//           "Complete Urine Examination (CUE)",
//         ],
//         testsCount: 59,
//         title: "MediBuddy Basic Health Checkup",
//       },
//       {
//         availableAt: "Home",
//         category: "popular",
//         couponCode: "LABS10",
//         discount: "53% OFF",
//         discountedPrice: 1399,
//         fasting: "10 - 12 Hrs",
//         id: 2,
//         is80DEligible: true,
//         offer: "Hurry! Flat 5% Off",
//         originalPrice: 2999,
//         reportsTime: "24 - 48 Hrs",
//         tests: [
//           "Thyroid &amp; Lipid Profile",
//           "Kidney &amp; Liver function tests",
//         ],
//         testsCount: 81,
//         title: "MediBuddy Full Body Health Checkup",
//       },
//       {
//         availableAt: "Home",
//         category: "popular",
//         couponCode: "LABS10",
//         discount: "50% OFF",
//         discountedPrice: 2499,
//         fasting: "10 - 12 Hrs",
//         id: 3,
//         is80DEligible: true,
//         offer: "Hurry! Flat 5% Off",
//         originalPrice: 4999,
//         reportsTime: "24 - 48 Hrs",
//         tests: ["Vitamin D &amp; B12", "Thyroid &amp; Lipid profile"],
//         testsCount: 85,
//         title: "Comprehensive Full Body Checkup with Vitamin D &amp; B12",
//       },
//       {
//         availableAt: "Home",
//         category: "popular",
//         couponCode: "LABS10",
//         discount: "4% OFF",
//         discountedPrice: 4830,
//         fasting: "10 - 12 Hrs",
//         id: 5,
//         is80DEligible: true,
//         offer: "Hurry! Flat 5% Off",
//         originalPrice: 5072,
//         reportsTime: "24 - 48 Hrs",
//         tests: [
//           "Complete Blood Count (CBC with P.Smear)",
//           "Glycosylated Hemoglobin (HBA1c)",
//         ],
//         testsCount: 64,
//         title: "Medibuddy Healthy Advance Package with Vitamin D",
//       },
//       {
//         availableAt: "Home",
//         category: "popular",
//         couponCode: "LABS10",
//         discount: "4% OFF",
//         discountedPrice: 3999,
//         fasting: "Not Required",
//         id: 6,
//         is80DEligible: true,
//         offer: "Hurry! Flat 5% Off",
//         originalPrice: 4199,
//         reportsTime: "24 - 48 Hrs",
//         tests: ["Urine Examination", "Kidney &amp; Liver Function Test"],
//         testsCount: 64,
//         title: "Medibuddy Full Body Essential Checkup",
//       },
//       {
//         availableAt: "Home",
//         category: "popular",
//         couponCode: "LABS10",
//         discount: "4% OFF",
//         discountedPrice: 4997,
//         fasting: "10 - 12 Hrs",
//         id: 7,
//         is80DEligible: true,
//         offer: "Hurry! Flat 5% Off",
//         originalPrice: 5247,
//         reportsTime: "24 - 48 Hrs",
//         tests: ["Iron Studies", "HBA1C"],
//         testsCount: 85,
//         title: "Medibuddy Fit Health Check-up",
//       },
//       {
//         availableAt: "Home",
//         category: "popular",
//         couponCode: "LABS10",
//         discount: "37% OFF",
//         discountedPrice: 2199,
//         fasting: "8 - 10 Hrs",
//         id: 8,
//         is80DEligible: true,
//         offer: "Hurry! Flat 5% Off",
//         originalPrice: 3499,
//         reportsTime: "24 - 48 Hrs",
//         tests: ["Vitamin B12 &amp; D", "Glucose Fasting (FBS)"],
//         testsCount: 81,
//         title: "Medibuddy 360 Health Check-up",
//       },
//       {
//         availableAt: "Home",
//         category: "popular",
//         couponCode: "LABS10",
//         discount: "4% OFF",
//         discountedPrice: 4663,
//         fasting: "10 - 12 Hrs",
//         id: 9,
//         is80DEligible: true,
//         offer: "Hurry! Flat 5% Off",
//         originalPrice: 4897,
//         reportsTime: "24 - 48 Hrs",
//         tests: ["Complete Urine Examination", "ESR - EDTA whole blood"],
//         testsCount: 77,
//         title: "Medibuddy Swasth Health Check-up",
//       },
//       {
//         availableAt: "Home",
//         category: "popular",
//         couponCode: "LABS10",
//         discount: "17% OFF",
//         discountedPrice: 1899,
//         fasting: "10 - 12 Hrs",
//         id: 10,
//         is80DEligible: true,
//         offer: "Hurry! Flat 5% Off",
//         originalPrice: 2299,
//         reportsTime: "10 - 12 Hrs",
//         tests: ["Complete Blood Count", "Kidney Function test (KFT)"],
//         testsCount: 59,
//         title: "MediBuddy Basic Health Checkup for Two",
//       },
//       {
//         availableAt: "Home",
//         category: "popular",
//         couponCode: "LABS10",
//         discount: "30% OFF",
//         discountedPrice: 3499,
//         fasting: "10 - 12 Hrs",
//         id: 11,
//         is80DEligible: true,
//         offer: "Hurry! Flat 5% Off",
//         originalPrice: 4999,
//         reportsTime: "24 - 48 Hrs",
//         tests: ["Vitamin D &amp; B12", "Iron Studies"],
//         testsCount: 96,
//         title: "Medibuddy Complete Health Check-up",
//       },
//       {
//         availableAt: "Home",
//         category: "popular",
//         couponCode: "LABS10",
//         discount: "50% OFF",
//         discountedPrice: 999,
//         fasting: "6 - 8 Hrs",
//         id: 44,
//         is80DEligible: true,
//         offer: "Hurry! Flat 5% Off",
//         originalPrice: 1999,
//         reportsTime: "24 - 48 Hrs",
//         tests: [
//           "Complete Blood Count (CBC) - EDTA Whole Blood",
//           "Complete Urine Examination (CUE) - Spot Urine",
//         ],
//         testsCount: 44,
//         title: "Medibuddy Swift Health Checkup",
//       },
//       {
//         availableAt: "Home",
//         category: "popular",
//         couponCode: "LABS10",
//         discount: "50% OFF",
//         discountedPrice: 2299,
//         fasting: "10 - 12 Hrs",
//         id: 45,
//         is80DEligible: true,
//         offer: "Hurry! Flat 5% Off",
//         originalPrice: 4599,
//         reportsTime: "24 - 48 Hrs",
//         tests: ["Iron Urea Uric Acid - Serum", "Vitamin D &amp; B12"],
//         testsCount: 88,
//         title: "Women's Primary Prevention Health Checkup",
//       },
//       {
//         availableAt: "Center",
//         category: "popular",
//         couponCode: "LABS10",
//         discount: "23% OFF",
//         discountedPrice: 2580,
//         fasting: "10 - 12 Hrs",
//         id: 46,
//         includes: [
//           {
//             icon: "https://www.medibuddy.in/assets/icons/corpLabs/radiology-icon.svg",
//             id: 1,
//             name: "Radiology",
//           },
//           {
//             icon: "https://www.medibuddy.in/assets/icons/doctor.svg",
//             id: 2,
//             name: "2 Consultations",
//           },
//         ],
//         is80DEligible: true,
//         offer: "Hurry! Flat 5% Off",
//         originalPrice: 3354,
//         reportsTime: "24 - 48 Hrs",
//         tests: ["2D Echo/Doppler Study", "Ultrasound &amp; ECG"],
//         testsCount: 46,
//         title: "MB Pack 1",
//       },
//       {
//         availableAt: "Home",
//         category: "popular",
//         couponCode: "LABS10",
//         discount: "48% OFF",
//         discountedPrice: 1799,
//         fasting: "6 - 8 Hrs",
//         id: 47,
//         is80DEligible: true,
//         offer: "Hurry! Flat 5% Off",
//         originalPrice: 3499,
//         reportsTime: "24 - 48 Hrs",
//         tests: ["Calcium Phosphorus - Serum", "Glycosylated Hemoglobin"],
//         testsCount: 82,
//         title: "MediBuddy Advance Health Checkup",
//       },
//       {
//         availableAt: "Home",
//         category: "popular",
//         couponCode: "LABS10",
//         discount: "51% OFF",
//         discountedPrice: 1299,
//         fasting: "10 - 12 Hrs",
//         id: 48,
//         is80DEligible: true,
//         offer: "Hurry! Flat 5% Off",
//         originalPrice: 2699,
//         reportsTime: "24 - 48 Hrs",
//         tests: ["Glucose Fasting (FBS)", "Triglycerides - Serum"],
//         testsCount: 54,
//         title: "MediBuddy Diabetes Screening",
//       },
//       {
//         availableAt: "Home",
//         category: "popular",
//         couponCode: "LABS10",
//         discount: "50% OFF",
//         discountedPrice: 3499,
//         fasting: "10 - 12 Hrs",
//         id: 49,
//         is80DEligible: true,
//         offer: "Hurry! Flat 5% Off",
//         originalPrice: 6999,
//         reportsTime: "24 - 48 Hrs",
//         tests: [
//           "Complete Blood Count (CBC) - EDTA Whole Blood",
//           "Complete Urine Examination (CUE) - Spot Urine",
//         ],
//         testsCount: 92,
//         title: "MediBuddy Young Male Health Checkup",
//       },
//       {
//         availableAt: "Home",
//         category: "popular",
//         couponCode: "LABS10",
//         discount: "50% OFF",
//         discountedPrice: 2299,
//         fasting: "10 - 12 Hrs",
//         id: 50,
//         is80DEligible: true,
//         offer: "Hurry! Flat 5% Off",
//         originalPrice: 4599,
//         reportsTime: "24 - 48 Hrs",
//         tests: [
//           "Complete Blood Count (CBC) - EDTA Whole Blood",
//           "Complete Urine Examination (CUE) - Spot Urine",
//         ],
//         testsCount: 85,
//         title: "MediBuddy Prime Comprehensive Health Checkup",
//       },
//       {
//         availableAt: "Home",
//         category: "popular",
//         couponCode: "LABS10",
//         discount: "35% OFF",
//         discountedPrice: 1299,
//         fasting: "6 - 8 Hrs",
//         id: 51,
//         is80DEligible: true,
//         offer: "Hurry! Flat 5% Off",
//         originalPrice: 1999,
//         reportsTime: "24 - 48 Hrs",
//         tests: [
//           "Complete Blood Count (CBC) - EDTA Whole Blood",
//           "Complete Urine Examination (CUE) - Spot Urine",
//         ],
//         testsCount: 44,
//         title: "Medibuddy Smart Health Checkup",
//       },
//       {
//         availableAt: "Home",
//         category: "popular",
//         couponCode: "LABS10",
//         discount: "51% OFF",
//         discountedPrice: 2299,
//         fasting: "10 - 12 Hrs",
//         id: 52,
//         is80DEligible: true,
//         offer: "Hurry! Flat 5% Off",
//         originalPrice: 4699,
//         reportsTime: "24 - 48 Hrs",
//         tests: ["Creatinine - Serum", "Prostate Specific Antigen"],
//         testsCount: 88,
//         title: "Master Full Body Health Checkup - Male (with cancer screening)",
//       },
//       {
//         availableAt: "Home",
//         category: "popular",
//         couponCode: "LABS10",
//         discount: "37% OFF",
//         discountedPrice: 1699,
//         fasting: "10 - 12 Hrs",
//         id: 53,
//         is80DEligible: true,
//         offer: "Hurry! Flat 5% Off",
//         originalPrice: 2699,
//         reportsTime: "24 - 48 Hrs",
//         tests: [
//           "Complete Blood Count (CBC) - EDTA Whole Blood",
//           "Complete Urine Examination (CUE) - Spot Urine",
//         ],
//         testsCount: 60,
//         title: "MediBuddy Basic Extended Health Check-up",
//       },
//       {
//         availableAt: "Home, Center",
//         category: "popular",
//         couponCode: "LABS10",
//         discount: "8% OFF",
//         discountedPrice: 2199,
//         fasting: "10 - 12 Hrs",
//         id: 54,
//         is80DEligible: true,
//         offer: "Hurry! Flat 5% Off",
//         originalPrice: 2399,
//         reportsTime: "24 - 48 Hrs",
//         tests: [
//           "Complete Blood Count (CBC) - EDTA Whole Blood",
//           "Complete Urine Examination (CUE) - Spot Urine",
//         ],
//         testsCount: 81,
//         title: "MediBuddy Full Body Health Checkup",
//       },
//       {
//         availableAt: "Home",
//         category: "popular",
//         couponCode: "LABS10",
//         discount: "5% OFF",
//         discountedPrice: 3299,
//         fasting: "10 - 12 Hrs",
//         id: 55,
//         is80DEligible: true,
//         offer: "Hurry! Flat 5% Off",
//         originalPrice: 3499,
//         reportsTime: "24 - 48 Hrs",
//         tests: [
//           "Complete Blood Count (CBC) - EDTA Whole Blood",
//           "Complete Urine Examination (CUE) - Spot Urine",
//         ],
//         testsCount: 84,
//         title: "Medibuddy Prime Health Checkup",
//       },
//     ],
//   },
//   {
//     category: "stress",
//     items: [
//       {
//         availableAt: "Home",
//         category: "stress",
//         couponCode: "LABS10",
//         discount: "40% OFF",
//         discountedPrice: 899,
//         fasting: "10 - 12 Hrs",
//         id: 4,
//         is80DEligible: true,
//         offer: "Hurry! Flat 5% Off",
//         originalPrice: 1499,
//         reportsTime: "24 - 48 Hrs",
//         tests: ["Haemogram (CBC+ESR)", "Cortisol - Serum"],
//         testsCount: 27,
//         title: "Stress Level Package",
//       },
//       {
//         availableAt: "Home",
//         category: "stress",
//         couponCode: "LABS10",
//         discount: "40% OFF",
//         discountedPrice: 899,
//         fasting: "10 - 12 Hrs",
//         id: 38,
//         is80DEligible: true,
//         offer: "Hurry! Flat 5% Off",
//         originalPrice: 1499,
//         reportsTime: "24 - 48 Hrs",
//         tests: ["Haemogram (CBC+ESR)", "Cortisol - Serum"],
//         testsCount: 27,
//         title: "Stress Level Package",
//       },
//     ],
//   },
//   {
//     category: "full_body",
//     items: [
//       {
//         availableAt: "Home",
//         category: "full_body",
//         couponCode: "LABS10",
//         discount: "53% OFF",
//         discountedPrice: 1399,
//         fasting: "10 - 12 Hrs",
//         id: 12,
//         is80DEligible: true,
//         offer: "Hurry! Flat 5% Off",
//         originalPrice: 2999,
//         reportsTime: "24 - 48 Hrs",
//         tests: [
//           "Thyroid &amp; Lipid Profile",
//           "Kidney &amp; Liver function tests",
//         ],
//         testsCount: 81,
//         title: "MediBuddy Full Body Health Checkup",
//       },
//       {
//         availableAt: "Home",
//         category: "full_body",
//         couponCode: "LABS10",
//         discount: "50% OFF",
//         discountedPrice: 2499,
//         fasting: "10 - 12 Hrs",
//         id: 13,
//         is80DEligible: true,
//         offer: "Hurry! Flat 5% Off",
//         originalPrice: 4999,
//         reportsTime: "24 - 48 Hrs",
//         tests: ["Vitamin D &amp; B12", "Thyroid &amp; Lipid profile"],
//         testsCount: 85,
//         title: "Comprehensive Full Body Checkup with Vitamin D &amp; B12",
//       },
//       {
//         availableAt: "Home",
//         category: "full_body",
//         couponCode: "LABS10",
//         discount: "4% OFF",
//         discountedPrice: 3999,
//         fasting: "Not Required",
//         id: 14,
//         is80DEligible: true,
//         offer: "Hurry! Flat 5% Off",
//         originalPrice: 4199,
//         reportsTime: "24 - 48 Hrs",
//         tests: ["Urine Examination", "Kidney &amp; Liver Function Test"],
//         testsCount: 64,
//         title: "Medibuddy Full Body Essential Checkup",
//       },
//       {
//         availableAt: "Home",
//         category: "full_body",
//         couponCode: "LABS10",
//         discount: "4% OFF",
//         discountedPrice: 4997,
//         fasting: "10 - 12 Hrs",
//         id: 15,
//         is80DEligible: true,
//         offer: "Hurry! Flat 5% Off",
//         originalPrice: 5247,
//         reportsTime: "24 - 48 Hrs",
//         tests: ["Iron Studies", "HBA1C"],
//         testsCount: 85,
//         title: "Medibuddy Fit Health Check-up",
//       },
//       {
//         availableAt: "Home",
//         category: "full_body",
//         couponCode: "LABS10",
//         discount: "37% OFF",
//         discountedPrice: 2199,
//         fasting: "8 - 10 Hrs",
//         id: 16,
//         is80DEligible: true,
//         offer: "Hurry! Flat 5% Off",
//         originalPrice: 3499,
//         reportsTime: "24 - 48 Hrs",
//         tests: ["Vitamin B12 &amp; D", "Glucose Fasting (FBS)"],
//         testsCount: 81,
//         title: "Medibuddy 360 Health Check-up",
//       },
//       {
//         availableAt: "Home",
//         category: "full_body",
//         couponCode: "LABS10",
//         discount: "4% OFF",
//         discountedPrice: 4663,
//         fasting: "10 - 12 Hrs",
//         id: 17,
//         is80DEligible: true,
//         offer: "Hurry! Flat 5% Off",
//         originalPrice: 4897,
//         reportsTime: "24 - 48 Hrs",
//         tests: ["Complete Urine Examination", "ESR - EDTA whole blood"],
//         testsCount: 77,
//         title: "Medibuddy Swasth Health Check-up",
//       },
//       {
//         availableAt: "Home",
//         category: "full_body",
//         couponCode: "LABS10",
//         discount: "51% OFF",
//         discountedPrice: 2299,
//         fasting: "10 - 12 Hrs",
//         id: 18,
//         is80DEligible: true,
//         offer: "Hurry! Flat 5% Off",
//         originalPrice: 4699,
//         reportsTime: "24 - 48 Hrs",
//         tests: ["Creatinine - Serum", "Prostate Specific Antigen"],
//         testsCount: 88,
//         title: "Master Full Body Health Checkup - Male (with cancer screening)",
//       },
//     ],
//   },
//   {
//     category: "diabetes",
//     items: [
//       {
//         availableAt: "Home",
//         category: "diabetes",
//         couponCode: "LABS10",
//         discount: "51% OFF",
//         discountedPrice: 1299,
//         fasting: "10 - 12 Hrs",
//         id: 19,
//         is80DEligible: true,
//         offer: "Hurry! Flat 5% Off",
//         originalPrice: 2699,
//         reportsTime: "24 - 48 Hrs",
//         tests: ["Glucose Fasting (FBS)", "Triglycerides - Serum"],
//         testsCount: 54,
//         title: "MediBuddy Diabetes Screening",
//       },
//     ],
//   },
//   {
//     category: "heart",
//     items: [
//       {
//         availableAt: "Home",
//         category: "heart",
//         couponCode: "LABS10",
//         discount: "50% OFF",
//         discountedPrice: 1099,
//         fasting: "10 - 12 Hrs",
//         id: 20,
//         is80DEligible: true,
//         offer: "Hurry! Flat 5% Off",
//         originalPrice: 2199,
//         reportsTime: "24 - 48 Hrs",
//         tests: [
//           "Complete Blood Count (CBC with P.Smear) - EDTA Whole Blood",
//           "Glycosylated Hemoglobin (HBA1c) - EDTA Whole Blood",
//         ],
//         testsCount: 52,
//         title: "Medibuddy Cardiac Health Package With ECG - Basic",
//       },
//       {
//         availableAt: "Home",
//         category: "heart",
//         couponCode: "LABS10",
//         discount: "50% OFF",
//         discountedPrice: 1999,
//         fasting: "10 - 12 Hrs",
//         id: 21,
//         is80DEligible: true,
//         offer: "Hurry! Flat 5% Off",
//         originalPrice: 3999,
//         reportsTime: "24 - 48 Hrs",
//         tests: [
//           "Complete Blood Count (CBC with P.Smear) - EDTA Whole Blood",
//           "Glycosylated Hemoglobin (HBA1c) - EDTA Whole Blood",
//         ],
//         testsCount: 58,
//         title: "Medibuddy Cardiac Health Package With ECG - Comprehensive",
//       },
//     ],
//   },
//   {
//     category: "cancer",
//     items: [
//       {
//         availableAt: "Home",
//         category: "cancer",
//         couponCode: "LABS10",
//         discount: "51% OFF",
//         discountedPrice: 2299,
//         fasting: "10 - 12 Hrs",
//         id: 22,
//         is80DEligible: true,
//         offer: "Hurry! Flat 5% Off",
//         originalPrice: 4699,
//         reportsTime: "24 - 48 Hrs",
//         tests: ["Creatinine - Serum", "Prostate Specific Antigen"],
//         testsCount: 88,
//         title: "Master Full Body Health Checkup - Male (with cancer screening)",
//       },
//       {
//         availableAt: "Home",
//         category: "cancer",
//         couponCode: "LABS10",
//         discount: "27% OFF",
//         discountedPrice: 1599,
//         fasting: "10 - 12 Hrs",
//         id: 23,
//         is80DEligible: true,
//         offer: "Hurry! Flat 5% Off",
//         originalPrice: 2199,
//         reportsTime: "24 - 48 Hrs",
//         tests: ["Prostate Specific Antigen", "Bilirubin Profile"],
//         testsCount: 65,
//         title:
//           "MediBuddy Basic Extended Health Checkup With Cancer Screening Male",
//       },
//     ],
//   },
//   {
//     category: "alcohol",
//     items: [
//       {
//         availableAt: "Home",
//         category: "alcohol",
//         couponCode: "LABS10",
//         discount: "56% OFF",
//         discountedPrice: 1299,
//         fasting: "10 - 12 Hrs",
//         id: 24,
//         is80DEligible: true,
//         offer: "Hurry! Flat 5% Off",
//         originalPrice: 2999,
//         reportsTime: "24 - 48 Hrs",
//         tests: [
//           "Haemogram (CBC+ESR) - EDTA Whole Blood",
//           "Kidney Function Test (KFT) - Serum",
//         ],
//         testsCount: 61,
//         title: "Alcohol Impact Package",
//       },
//     ],
//   },
//   {
//     category: "smoker",
//     items: [
//       {
//         availableAt: "Home",
//         category: "smoker",
//         couponCode: "LABS10",
//         discount: "52% OFF",
//         discountedPrice: 2399,
//         fasting: "6 - 8 Hrs",
//         id: 25,
//         is80DEligible: true,
//         offer: "Hurry! Flat 5% Off",
//         originalPrice: 4999,
//         reportsTime: "24 - 48 Hrs",
//         tests: [
//           "Glycosylated Hemoglobin (HBA1c) - EDTA Whole Blood",
//           "Haemogram (CBC+ESR) - EDTA Whole Blood",
//         ],
//         testsCount: 72,
//         title: "Smokers Health Checkup",
//       },
//     ],
//   },
//   {
//     category: "vitamin",
//     items: [
//       {
//         availableAt: "Home",
//         category: "vitamin",
//         couponCode: "LABS10",
//         discount: "50% OFF",
//         discountedPrice: 2499,
//         fasting: "10 - 12 Hrs",
//         id: 26,
//         is80DEligible: true,
//         offer: "Hurry! Flat 5% Off",
//         originalPrice: 4999,
//         reportsTime: "24 - 48 Hrs",
//         tests: ["Vitamin D &amp; B12", "Thyroid &amp; Lipid profile"],
//         testsCount: 85,
//         title: "Comprehensive Full Body Checkup with Vitamin D &amp; B12",
//       },
//       {
//         availableAt: "Home",
//         category: "vitamin",
//         couponCode: "",
//         discount: "0% OFF",
//         discountedPrice: 660,
//         fasting: "10 - 12 Hrs",
//         id: 27,
//         is80DEligible: false,
//         offer: "",
//         originalPrice: 660,
//         reportsTime: "24 - 48 Hrs",
//         tests: [
//           "Complete Blood Count (CBC) - EDTA Whole Blood",
//           "Complete Urine Examination (CUE) - Spot Urine",
//         ],
//         testsCount: 50,
//         title: "MB Pack 32",
//       },
//     ],
//   },
//   {
//     category: "joint",
//     items: [
//       {
//         availableAt: "Home",
//         category: "joint",
//         couponCode: "LABS10",
//         discount: "30% OFF",
//         discountedPrice: 2099,
//         fasting: "6 - 8 Hrs",
//         id: 28,
//         is80DEligible: true,
//         offer: "Hurry! Flat 5% Off",
//         originalPrice: 2999,
//         reportsTime: "24 - 48 Hrs",
//         tests: [
//           "Complete Blood Count (CBC with P.Smear) - EDTA Whole Blood",
//           "Glycosylated Hemoglobin (HBA1c) - EDTA Whole Blood",
//         ],
//         testsCount: 69,
//         title: "Joint Pain Package",
//       },
//     ],
//   },
//   {
//     category: "weight",
//     items: [
//       {
//         availableAt: "Home",
//         category: "weight",
//         couponCode: "LABS10",
//         discount: "53% OFF",
//         discountedPrice: 2999,
//         fasting: "10 - 12 Hrs",
//         id: 29,
//         is80DEligible: true,
//         offer: "Hurry! Flat 5% Off",
//         originalPrice: 6499,
//         reportsTime: "24 - 48 Hrs",
//         tests: [
//           "Complete Blood Count (CBC with P.Smear) - EDTA Whole Blood",
//           "Glycosylated Hemoglobin (HBA1c) - EDTA Whole Blood",
//         ],
//         testsCount: 49,
//         title: "Weight Management Package",
//       },
//     ],
//   },
//   {
//     category: "women_health",
//     items: [
//       {
//         availableAt: "Home",
//         category: "women_health",
//         couponCode: "LABS10",
//         discount: "50% OFF",
//         discountedPrice: 3499,
//         fasting: "10 - 12 Hrs",
//         id: 30,
//         is80DEligible: true,
//         offer: "Hurry! Flat 5% Off",
//         originalPrice: 6999,
//         reportsTime: "24 - 48 Hrs",
//         tests: [
//           "Complete Blood Count (CBC) - EDTA Whole Blood",
//           "Complete Urine Examination (CUE) - Spot Urine",
//         ],
//         testsCount: 92,
//         title: "Women’s Staying Strong Health Checkup",
//       },
//       {
//         availableAt: "Home",
//         category: "women_health",
//         couponCode: "LABS10",
//         discount: "50% OFF",
//         discountedPrice: 4699,
//         fasting: "10 - 12 Hrs",
//         id: 31,
//         is80DEligible: true,
//         offer: "Hurry! Flat 5% Off",
//         originalPrice: 9499,
//         reportsTime: "24 - 48 Hrs",
//         tests: [
//           "Complete Blood Count (CBC with P.Smear) - EDTA Whole Blood",
//           "Complete Urine Examination (CUE) - Spot Urine",
//         ],
//         testsCount: 103,
//         title: "Women’s Golden Gift Health Checkup",
//       },
//       {
//         availableAt: "Home",
//         category: "women_health",
//         couponCode: "LABS10",
//         discount: "50% OFF",
//         discountedPrice: 2299,
//         fasting: "10 - 12 Hrs",
//         id: 32,
//         is80DEligible: true,
//         offer: "Hurry! Flat 5% Off",
//         originalPrice: 4599,
//         reportsTime: "24 - 48 Hrs",
//         tests: ["Iron Urea Uric Acid - Serum", "Vitamin D &amp; B12"],
//         testsCount: 88,
//         title: "Women's Primary Prevention Health Checkup",
//       },
//       {
//         availableAt: "Home",
//         category: "women_health",
//         couponCode: "LABS10",
//         discount: "50% OFF",
//         discountedPrice: 1999,
//         fasting: "6 - 8 Hrs",
//         id: 33,
//         is80DEligible: true,
//         offer: "Hurry! Flat 5% Off",
//         originalPrice: 3999,
//         reportsTime: "24 - 48 Hrs",
//         tests: [
//           "Thyroid Profile (T3,T4 &amp; TSH) - Serum",
//           "Anti Mullerian Hormone (AMH) - Serum",
//         ],
//         testsCount: 9,
//         title: "Hormone Profile - Female",
//       },
//     ],
//   },
//   {
//     category: "men_health",
//     items: [
//       {
//         availableAt: "Home",
//         category: "men_health",
//         couponCode: "LABS10",
//         discount: "50% OFF",
//         discountedPrice: 3499,
//         fasting: "10 - 12 Hrs",
//         id: 34,
//         is80DEligible: true,
//         offer: "Hurry! Flat 5% Off",
//         originalPrice: 6999,
//         reportsTime: "24 - 48 Hrs",
//         tests: [
//           "Complete Blood Count (CBC) - EDTA Whole Blood",
//           "Complete Urine Examination (CUE) - Spot Urine",
//         ],
//         testsCount: 92,
//         title: "MediBuddy Young Male Health Checkup",
//       },
//       {
//         availableAt: "Home",
//         category: "men_health",
//         couponCode: "LABS10",
//         discount: "50% OFF",
//         discountedPrice: 4699,
//         fasting: "10 - 12 Hrs",
//         id: 35,
//         is80DEligible: true,
//         offer: "Hurry! Flat 5% Off",
//         originalPrice: 9499,
//         reportsTime: "24 - 48 Hrs",
//         tests: [
//           "Complete Blood Count (CBC with P.Smear) - EDTA Whole Blood",
//           "Complete Urine Examination (CUE) - Spot Urine",
//         ],
//         testsCount: 107,
//         title: "MediBuddy Elderly Male Health Checkup",
//       },
//     ],
//   },
//   {
//     category: "sexual_wellness",
//     items: [
//       {
//         availableAt: "Home, Center",
//         category: "sexual_wellness",
//         couponCode: "LABS10",
//         discount: "49% OFF",
//         discountedPrice: 2699,
//         fasting: "6 - 8 Hrs",
//         id: 36,
//         is80DEligible: true,
//         offer: "Hurry! Flat 5% Off",
//         originalPrice: 5299,
//         reportsTime: "24 - 48 Hrs",
//         tests: [
//           "Chlamydia Antibodies IgG - Serum",
//           "Herpes Simplex Virus 1 &amp; 2 IgG - Serum",
//         ],
//         testsCount: 5,
//         title: "STD Panel",
//       },
//     ],
//   },
//   {
//     category: "hair_care",
//     items: [
//       {
//         availableAt: "Home",
//         category: "hair_care",
//         couponCode: "LABS10",
//         discount: "50% OFF",
//         discountedPrice: 1499,
//         fasting: "6 - 8 Hrs",
//         id: 37,
//         is80DEligible: true,
//         offer: "Hurry! Flat 5% Off",
//         originalPrice: 2999,
//         reportsTime: "24 - 48 Hrs",
//         tests: ["Haemogram (CBC+ESR)", "Glycosylated Haemoglobin"],
//         testsCount: 35,
//         title: "Hair Care Package",
//       },
//     ],
//   },
//   {
//     category: "liver",
//     items: [
//       {
//         availableAt: "Home",
//         category: "liver",
//         couponCode: "LABS10",
//         discount: "53% OFF",
//         discountedPrice: 1399,
//         fasting: "10 - 12 Hrs",
//         id: 39,
//         is80DEligible: true,
//         offer: "Hurry! Flat 5% Off",
//         originalPrice: 2999,
//         reportsTime: "24 - 48 Hrs",
//         tests: [
//           "Thyroid &amp; Lipid Profile",
//           "Kidney &amp; Liver function tests",
//         ],
//         testsCount: 81,
//         title: "MediBuddy Full body Health Checkup",
//       },
//     ],
//   },
//   {
//     category: "senior_citizen",
//     items: [
//       {
//         availableAt: "Home",
//         category: "senior_citizen",
//         couponCode: "LABS10",
//         discount: "50% OFF",
//         discountedPrice: 4699,
//         fasting: "10 - 12 Hrs",
//         id: 40,
//         is80DEligible: true,
//         offer: "Hurry! Flat 5% Off",
//         originalPrice: 9499,
//         reportsTime: "24 - 48 Hrs",
//         tests: [
//           "Complete Blood Count (CBC with P.Smear) - EDTA Whole Blood",
//           "Complete Urine Examination (CUE) - Spot Urine",
//         ],
//         testsCount: 103,
//         title: "Women’s Golden Gift Health Checkup",
//       },
//       {
//         availableAt: "Home",
//         category: "senior_citizen",
//         couponCode: "LABS10",
//         discount: "50% OFF",
//         discountedPrice: 4699,
//         fasting: "10 - 12 Hrs",
//         id: 41,
//         is80DEligible: true,
//         offer: "Hurry! Flat 5% Off",
//         originalPrice: 9499,
//         reportsTime: "24 - 48 Hrs",
//         tests: [
//           "Complete Blood Count (CBC with P.Smear) - EDTA Whole Blood",
//           "Complete Urine Examination (CUE) - Spot Urine",
//         ],
//         testsCount: 107,
//         title: "MediBuddy Elderly Male Health Checkup",
//       },
//     ],
//   },
//   {
//     category: "kids",
//     items: [
//       {
//         availableAt: "Home",
//         category: "kids",
//         couponCode: "LABS10",
//         discount: "50% OFF",
//         discountedPrice: 1999,
//         fasting: "10 - 12 Hrs",
//         id: 42,
//         is80DEligible: true,
//         offer: "Hurry! Flat 5% Off",
//         originalPrice: 3999,
//         reportsTime: "24 - 48 Hrs",
//         tests: [
//           "Complete Blood Count (CBC) - EDTA Whole Blood",
//           "Complete Urine Examination (CUE) - Spot Urine",
//         ],
//         testsCount: 58,
//         title: "MediBuddy Kid's Exclusive Health Checkup",
//       },
//       {
//         availableAt: "Home",
//         category: "kids",
//         couponCode: "LABS10",
//         discount: "43% OFF",
//         discountedPrice: 899,
//         fasting: "10 - 12 Hrs",
//         id: 43,
//         is80DEligible: true,
//         offer: "Hurry! Flat 5% Off",
//         originalPrice: 1599,
//         reportsTime: "24 - 48 Hrs",
//         tests: [
//           "Blood Grouping &amp; Rh Type - EDTA Whole Blood",
//           "Complete Blood Count (CBC with P.Smear) - EDTA Whole Blood",
//         ],
//         testsCount: 30,
//         title: "MediBuddy Kid's Basic Health Check-up",
//       },
//     ],
//   },
//   {
//     category: "center_visit",
//     items: [
//       {
//         availableAt: "Center",
//         category: "center_visit",
//         couponCode: "LABS10",
//         discount: "23% OFF",
//         discountedPrice: 2580,
//         fasting: "10 - 12 Hrs",
//         id: 56,
//         includes: [
//           {
//             icon: "https://www.medibuddy.in/assets/icons/corpLabs/radiology-icon.svg",
//             id: 1,
//             name: "Radiology",
//           },
//           {
//             icon: "https://www.medibuddy.in/assets/icons/doctor.svg",
//             id: 2,
//             name: "2 Consultations",
//           },
//         ],
//         is80DEligible: true,
//         offer: "Hurry! Flat 5% Off",
//         originalPrice: 3354,
//         reportsTime: "24 - 48 Hrs",
//         tests: ["2D Echo/Doppler Study", "Ultrasound &amp; ECG"],
//         testsCount: 46,
//         title: "MB Pack 1",
//       },
//       {
//         availableAt: "Center",
//         category: "center_visit",
//         discount: "23% OFF",
//         discountedPrice: 1820,
//         fasting: "10 - 12 Hrs",
//         id: 57,
//         includes: [
//           {
//             icon: "https://www.medibuddy.in/assets/icons/corpLabs/radiology-icon.svg",
//             id: 1,
//             name: "Radiology",
//           },
//           {
//             icon: "https://www.medibuddy.in/assets/icons/doctor.svg",
//             id: 2,
//             name: "3 Consultations",
//           },
//         ],
//         originalPrice: 2366,
//         reportsTime: "24 - 48 Hrs",
//         tests: ["X-Ray Chest", "Pap Smear - Liquid Based"],
//         testsCount: 42,
//         title: "MB Pack 2",
//       },
//       {
//         availableAt: "Center",
//         category: "center_visit",
//         discount: "23% OFF",
//         discountedPrice: 1920,
//         fasting: "10 - 12 Hrs",
//         id: 58,
//         includes: [
//           {
//             icon: "https://www.medibuddy.in/assets/icons/corpLabs/radiology-icon.svg",
//             id: 1,
//             name: "Radiology",
//           },
//           {
//             icon: "https://www.medibuddy.in/assets/icons/doctor.svg",
//             id: 2,
//             name: "1 Consultation",
//           },
//         ],
//         originalPrice: 2496,
//         reportsTime: "24 - 48 Hrs",
//         tests: ["Ultrasound (Abdomen)", "Electrocardiogram (ECG)"],
//         testsCount: 44,
//         title: "MB Pack 3",
//       },
//       {
//         availableAt: "Center",
//         category: "center_visit",
//         discount: "23% OFF",
//         discountedPrice: 1050,
//         fasting: "10 - 12 Hrs",
//         id: 59,
//         includes: [
//           {
//             icon: "https://www.medibuddy.in/assets/icons/corpLabs/radiology-icon.svg",
//             id: 1,
//             name: "Radiology",
//           },
//           {
//             icon: "https://www.medibuddy.in/assets/icons/doctor.svg",
//             id: 2,
//             name: "2 Consultations",
//           },
//         ],
//         originalPrice: 1365,
//         reportsTime: "24 - 48 Hrs",
//         tests: ["X-Ray Chest", "Electrocardiogram (ECG)"],
//         testsCount: 37,
//         title: "MB Pack 11",
//       },
//       {
//         availableAt: "Center",
//         category: "center_visit",
//         couponCode: "LABS10",
//         discount: "23% OFF",
//         discountedPrice: 2300,
//         fasting: "10 - 12 Hrs",
//         id: 60,
//         includes: [
//           {
//             icon: "https://www.medibuddy.in/assets/icons/corpLabs/radiology-icon.svg",
//             id: 1,
//             name: "Radiology",
//           },
//           {
//             icon: "https://www.medibuddy.in/assets/icons/doctor.svg",
//             id: 2,
//             name: "3 Consultations",
//           },
//         ],
//         offer: "Hurry! Flat 5% Off",
//         originalPrice: 2990,
//         reportsTime: "24 - 48 Hrs",
//         tests: ["Ultrasound &amp; ECG", "Creatinine - Serum"],
//         testsCount: 47,
//         title: "MB Pack 12",
//       },
//       {
//         availableAt: "Center",
//         category: "center_visit",
//         discount: "23% OFF",
//         discountedPrice: 2230,
//         fasting: "10 - 12 Hrs",
//         id: 61,
//         includes: [
//           {
//             icon: "https://www.medibuddy.in/assets/icons/corpLabs/radiology-icon.svg",
//             id: 1,
//             name: "Radiology",
//           },
//           {
//             icon: "https://www.medibuddy.in/assets/icons/doctor.svg",
//             id: 2,
//             name: "3 Consultations",
//           },
//         ],
//         originalPrice: 2899,
//         reportsTime: "24 - 48 Hrs",
//         tests: [
//           "Complete Blood Count (CBC) - EDTA Whole Blood",
//           "2D Echo/Doppler Study",
//         ],
//         testsCount: 34,
//         title: "MB Pack 13",
//       },
//       {
//         availableAt: "Center",
//         category: "center_visit",
//         couponCode: "LABS10",
//         discount: "23% OFF",
//         discountedPrice: 1800,
//         fasting: "10 - 12 Hrs",
//         id: 62,
//         includes: [
//           {
//             icon: "https://www.medibuddy.in/assets/icons/corpLabs/radiology-icon.svg",
//             id: 1,
//             name: "Radiology",
//           },
//           {
//             icon: "https://www.medibuddy.in/assets/icons/doctor.svg",
//             id: 2,
//             name: "1 Consultation",
//           },
//         ],
//         offer: "Hurry! Flat 5% Off",
//         originalPrice: 2340,
//         reportsTime: "24 - 48 Hrs",
//         tests: ["Thyroid Profile", "ECG &amp; X-Ray Chest"],
//         testsCount: 50,
//         title: "MB Pack 14",
//       },
//       {
//         availableAt: "Center",
//         category: "center_visit",
//         discount: "23% OFF",
//         discountedPrice: 1900,
//         fasting: "10 - 12 Hrs",
//         id: 63,
//         includes: [
//           {
//             icon: "https://www.medibuddy.in/assets/icons/corpLabs/radiology-icon.svg",
//             id: 1,
//             name: "Radiology",
//           },
//           {
//             icon: "https://www.medibuddy.in/assets/icons/doctor.svg",
//             id: 2,
//             name: "3 Consultations",
//           },
//         ],
//         originalPrice: 2470,
//         reportsTime: "24 - 48 Hrs",
//         tests: [
//           "Bilirubin Profile (Total, Direct &amp; Indirect) - Serum",
//           "Complete Blood Count (CBC) - EDTA Whole Blood",
//         ],
//         testsCount: 45,
//         title: "MB Pack 15",
//       },
//       {
//         availableAt: "Center",
//         category: "center_visit",
//         discount: "23% OFF",
//         discountedPrice: 2500,
//         fasting: "10 - 12 Hrs",
//         id: 64,
//         includes: [
//           {
//             icon: "https://www.medibuddy.in/assets/icons/corpLabs/radiology-icon.svg",
//             id: 1,
//             name: "Radiology",
//           },
//           {
//             icon: "https://www.medibuddy.in/assets/icons/doctor.svg",
//             id: 2,
//             name: "1 Consultation",
//           },
//         ],
//         originalPrice: 3250,
//         reportsTime: "24 - 48 Hrs",
//         tests: [
//           "Bilirubin Profile (Total, Direct &amp; Indirect) - Serum",
//           "Complete Blood Count (CBC) - EDTA Whole Blood",
//         ],
//         testsCount: 47,
//         title: "MB Pack 16",
//       },
//       {
//         availableAt: "Center",
//         category: "center_visit",
//         couponCode: "LABS10",
//         discount: "23% OFF",
//         discountedPrice: 2800,
//         fasting: "10 - 12 Hrs",
//         id: 65,
//         includes: [
//           {
//             icon: "https://www.medibuddy.in/assets/icons/corpLabs/radiology-icon.svg",
//             id: 1,
//             name: "Radiology",
//           },
//           {
//             icon: "https://www.medibuddy.in/assets/icons/doctor.svg",
//             id: 2,
//             name: "3 Consultations",
//           },
//         ],
//         offer: "Hurry! Flat 5% Off",
//         originalPrice: 3640,
//         reportsTime: "24 - 48 Hrs",
//         tests: [
//           "Bilirubin Profile (Total, Direct &amp; Indirect) - Serum",
//           "Complete Blood Count (CBC) - EDTA Whole Blood",
//         ],
//         testsCount: 43,
//         title: "MB Pack 17",
//       },
//       {
//         availableAt: "Center",
//         category: "center_visit",
//         discount: "23% OFF",
//         discountedPrice: 4520,
//         fasting: "10 - 12 Hrs",
//         id: 66,
//         includes: [
//           {
//             icon: "https://www.medibuddy.in/assets/icons/corpLabs/radiology-icon.svg",
//             id: 1,
//             name: "Radiology",
//           },
//           {
//             icon: "https://www.medibuddy.in/assets/icons/doctor.svg",
//             id: 2,
//             name: "3 Consultations",
//           },
//         ],
//         originalPrice: 5876,
//         reportsTime: "24 - 48 Hrs",
//         tests: [
//           "Bilirubin Profile (Total, Direct &amp; Indirect) - Serum",
//           "Blood Grouping &amp; Rh Type - EDTA Whole Blood",
//         ],
//         testsCount: 59,
//         title: "MB Pack 21",
//       },
//       {
//         availableAt: "Center",
//         category: "center_visit",
//         couponCode: "LABS10",
//         discount: "23% OFF",
//         discountedPrice: 4100,
//         fasting: "10 - 12 Hrs",
//         id: 67,
//         includes: [
//           {
//             icon: "https://www.medibuddy.in/assets/icons/corpLabs/radiology-icon.svg",
//             id: 1,
//             name: "Radiology",
//           },
//           {
//             icon: "https://www.medibuddy.in/assets/icons/doctor.svg",
//             id: 2,
//             name: "4 Consultations",
//           },
//         ],
//         offer: "Hurry! Flat 5% Off",
//         originalPrice: 5330,
//         reportsTime: "24 - 48 Hrs",
//         tests: [
//           "Bilirubin Profile (Total, Direct &amp; Indirect) - Serum",
//           "Complete Blood Count (CBC) - EDTA Whole Blood",
//         ],
//         testsCount: 61,
//         title: "MB Pack 18",
//       },
//       {
//         availableAt: "Center",
//         category: "center_visit",
//         discount: "23% OFF",
//         discountedPrice: 3600,
//         fasting: "10 - 12 Hrs",
//         id: 68,
//         includes: [
//           {
//             icon: "https://www.medibuddy.in/assets/icons/corpLabs/radiology-icon.svg",
//             id: 1,
//             name: "Radiology",
//           },
//           {
//             icon: "https://www.medibuddy.in/assets/icons/doctor.svg",
//             id: 2,
//             name: "5 Consultations",
//           },
//         ],
//         originalPrice: 4680,
//         reportsTime: "24 - 48 Hrs",
//         tests: [
//           "Bilirubin Profile (Total, Direct &amp; Indirect) - Serum",
//           "Blood Grouping &amp; Rh Type - EDTA Whole Blood",
//         ],
//         testsCount: 51,
//         title: "MB Pack 19",
//       },
//       {
//         availableAt: "Center",
//         category: "center_visit",
//         couponCode: "LABS10",
//         discount: "23% OFF",
//         discountedPrice: 3300,
//         fasting: "10 - 12 Hrs",
//         id: 69,
//         includes: [
//           {
//             icon: "https://www.medibuddy.in/assets/icons/corpLabs/radiology-icon.svg",
//             id: 1,
//             name: "Radiology",
//           },
//           {
//             icon: "https://www.medibuddy.in/assets/icons/doctor.svg",
//             id: 2,
//             name: "4 Consultations",
//           },
//         ],
//         offer: "Hurry! Flat 5% Off",
//         originalPrice: 4290,
//         reportsTime: "24 - 48 Hrs",
//         tests: [
//           "Bilirubin Profile (Total, Direct &amp; Indirect) - Serum",
//           "Complete Blood Count (CBC) - EDTA Whole Blood",
//         ],
//         testsCount: 56,
//         title: "MB Pack 20",
//       },
//       {
//         availableAt: "Center",
//         category: "center_visit",
//         discount: "23% OFF",
//         discountedPrice: 5100,
//         fasting: "10 - 12 Hrs",
//         id: 70,
//         includes: [
//           {
//             icon: "https://www.medibuddy.in/assets/icons/corpLabs/radiology-icon.svg",
//             id: 1,
//             name: "Radiology",
//           },
//           {
//             icon: "https://www.medibuddy.in/assets/icons/doctor.svg",
//             id: 2,
//             name: "5 Consultations",
//           },
//         ],
//         originalPrice: 6630,
//         reportsTime: "24 - 48 Hrs",
//         tests: [
//           "Bilirubin Profile (Total, Direct &amp; Indirect) - Serum",
//           "Complete Blood Count (CBC) - EDTA Whole Blood",
//         ],
//         testsCount: 62,
//         title: "MB Pack 22",
//       },
//     ],
//   },
// ];


export const healthPackages = [
    {
      id: 1,
      title: "MediBuddy Basic Health Checkup",
      category: "popular",
      reportsTime: "24 - 48 Hrs",
      testsCount: 59,
      tests: ["Complete Blood Count (CBC)", "Complete Urine Examination (CUE)"],
      fasting: "10 - 12 Hrs",
      availableAt: "Home",
      originalPrice: 2299,
      discount: "52% OFF",
      discountedPrice: 1099,
      offer: "Hurry! Flat 5% Off",
      couponCode: "LABS10",
      is80DEligible: true,
    },
    {
      id: 2,
      title: "MediBuddy Full Body Health Checkup",
      category: "popular",
      reportsTime: "24 - 48 Hrs",
      testsCount: 81,
      tests: ["Thyroid & Lipid Profile", "Kidney & Liver function tests"],
      fasting: "10 - 12 Hrs",
      availableAt: "Home",
      originalPrice: 2999,
      discount: "53% OFF",
      discountedPrice: 1399,
      offer: "Hurry! Flat 5% Off",
      couponCode: "LABS10",
      is80DEligible: true,
    },
    {
      id: 3,
      title: "Comprehensive Full Body Checkup with Vitamin D & B12",
      category: "popular",
      reportsTime: "24 - 48 Hrs",
      testsCount: 85,
      tests: ["Vitamin D & B12", "Thyroid & Lipid profile"],
      fasting: "10 - 12 Hrs",
      availableAt: "Home",
      originalPrice: 4999,
      discount: "50% OFF",
      discountedPrice: 2499,
      offer: "Hurry! Flat 5% Off",
      couponCode: "LABS10",
      is80DEligible: true,
    },
    {
      id: 4,
      title: "Stress Level Package",
      category: "stress",
      reportsTime: "24 - 48 Hrs",
      testsCount: 27,
      tests: ["Haemogram (CBC+ESR)", "Cortisol - Serum"],
      fasting: "10 - 12 Hrs",
      availableAt: "Home",
      originalPrice: 1499,
      discount: "40% OFF",
      discountedPrice: 899,
      offer: "Hurry! Flat 5% Off",
      couponCode: "LABS10",
      is80DEligible: true,
    },
    {
      id: 5,
      title: "Medibuddy Healthy Advance Package with Vitamin D",
      category: "popular",
      reportsTime: "24 - 48 Hrs",
      testsCount: 64,
      tests: [
        "Complete Blood Count (CBC with P.Smear)",
        "Glycosylated Hemoglobin (HBA1c)",
      ],
      fasting: "10 - 12 Hrs",
      availableAt: "Home",
      originalPrice: 5072,
      discount: "4% OFF",
      discountedPrice: 4830,
      offer: "Hurry! Flat 5% Off",
      couponCode: "LABS10",
      is80DEligible: true,
    },
    {
      id: 6,
      title: "Medibuddy Full Body Essential Checkup",
      category: "popular",
      reportsTime: "24 - 48 Hrs",
      testsCount: 64,
      tests: ["Urine Examination", "Kidney & Liver Function Test"],
      fasting: "Not Required",
      availableAt: "Home",
      originalPrice: 4199,
      discount: "4% OFF",
      discountedPrice: 3999,
      offer: "Hurry! Flat 5% Off",
      couponCode: "LABS10",
      is80DEligible: true,
    },
    {
      id: 7,
      title: "Medibuddy Fit Health Check-up",
      category: "popular",
      reportsTime: "24 - 48 Hrs",
      testsCount: 85,
      tests: ["Iron Studies", "HBA1C"],
      fasting: "10 - 12 Hrs",
      availableAt: "Home",
      originalPrice: 5247,
      discount: "4% OFF",
      discountedPrice: 4997,
      offer: "Hurry! Flat 5% Off",
      couponCode: "LABS10",
      is80DEligible: true,
    },
    {
      id: 8,
      title: "Medibuddy 360 Health Check-up",
      category: "popular",
      reportsTime: "24 - 48 Hrs",
      testsCount: 81,
      tests: ["Vitamin B12 & D", "Glucose Fasting (FBS)"],
      fasting: "8 - 10 Hrs",
      availableAt: "Home",
      originalPrice: 3499,
      discount: "37% OFF",
      discountedPrice: 2199,
      offer: "Hurry! Flat 5% Off",
      couponCode: "LABS10",
      is80DEligible: true,
    },
    {
      id: 9,
      title: "Medibuddy Swasth Health Check-up",
      category: "popular",
      reportsTime: "24 - 48 Hrs",
      testsCount: 77,
      tests: ["Complete Urine Examination", "ESR - EDTA whole blood"],
      fasting: "10 - 12 Hrs",
      availableAt: "Home",
      originalPrice: 4897,
      discount: "4% OFF",
      discountedPrice: 4663,
      offer: "Hurry! Flat 5% Off",
      couponCode: "LABS10",
      is80DEligible: true,
    },
    {
      id: 10,
      title: "MediBuddy Basic Health Checkup for Two",
      category: "popular",
      reportsTime: "10 - 12 Hrs",
      testsCount: 59,
      tests: ["Complete Blood Count", "Kidney Function test (KFT)"],
      fasting: "10 - 12 Hrs",
      availableAt: "Home",
      originalPrice: 2299,
      discount: "17% OFF",
      discountedPrice: 1899,
      offer: "Hurry! Flat 5% Off",
      couponCode: "LABS10",
      is80DEligible: true,
    },
    {
      id: 11,
      title: "Medibuddy Complete Health Check-up",
      category: "popular",
      reportsTime: "24 - 48 Hrs",
      testsCount: 96,
      tests: ["Vitamin D & B12", "Iron Studies"],
      fasting: "10 - 12 Hrs",
      availableAt: "Home",
      originalPrice: 4999,
      discount: "30% OFF",
      discountedPrice: 3499,
      offer: "Hurry! Flat 5% Off",
      couponCode: "LABS10",
      is80DEligible: true,
    },
    {
      id: 12,
      title: "MediBuddy Full Body Health Checkup",
      category: "full_body",
      reportsTime: "24 - 48 Hrs",
      testsCount: 81,
      tests: ["Thyroid & Lipid Profile", "Kidney & Liver function tests"],
      fasting: "10 - 12 Hrs",
      availableAt: "Home",
      originalPrice: 2999,
      discount: "53% OFF",
      discountedPrice: 1399,
      offer: "Hurry! Flat 5% Off",
      couponCode: "LABS10",
      is80DEligible: true,
    },
    {
      id: 13,
      title: "Comprehensive Full Body Checkup with Vitamin D & B12",
      category: "full_body",
      reportsTime: "24 - 48 Hrs",
      testsCount: 85,
      tests: ["Vitamin D & B12", "Thyroid & Lipid profile"],
      fasting: "10 - 12 Hrs",
      availableAt: "Home",
      originalPrice: 4999,
      discount: "50% OFF",
      discountedPrice: 2499,
      offer: "Hurry! Flat 5% Off",
      couponCode: "LABS10",
      is80DEligible: true,
    },
    {
      id: 14,
      title: "Medibuddy Full Body Essential Checkup",
      category: "full_body",
      reportsTime: "24 - 48 Hrs",
      testsCount: 64,
      tests: ["Urine Examination", "Kidney & Liver Function Test"],
      fasting: "Not Required",
      availableAt: "Home",
      originalPrice: 4199,
      discount: "4% OFF",
      discountedPrice: 3999,
      offer: "Hurry! Flat 5% Off",
      couponCode: "LABS10",
      is80DEligible: true,
    },
    {
      id: 15,
      title: "Medibuddy Fit Health Check-up",
      category: "full_body",
      reportsTime: "24 - 48 Hrs",
      testsCount: 85,
      tests: ["Iron Studies", "HBA1C"],
      fasting: "10 - 12 Hrs",
      availableAt: "Home",
      originalPrice: 5247,
      discount: "4% OFF",
      discountedPrice: 4997,
      offer: "Hurry! Flat 5% Off",
      couponCode: "LABS10",
      is80DEligible: true,
    },
    {
      id: 16,
      title: "Medibuddy 360 Health Check-up",
      category: "full_body",
      reportsTime: "24 - 48 Hrs",
      testsCount: 81,
      tests: ["Vitamin B12 & D", "Glucose Fasting (FBS)"],
      fasting: "8 - 10 Hrs",
      availableAt: "Home",
      originalPrice: 3499,
      discount: "37% OFF",
      discountedPrice: 2199,
      offer: "Hurry! Flat 5% Off",
      couponCode: "LABS10",
      is80DEligible: true,
    },
    {
      id: 17,
      title: "Medibuddy Swasth Health Check-up",
      category: "full_body",
      reportsTime: "24 - 48 Hrs",
      testsCount: 77,
      tests: ["Complete Urine Examination", "ESR - EDTA whole blood"],
      fasting: "10 - 12 Hrs",
      availableAt: "Home",
      originalPrice: 4897,
      discount: "4% OFF",
      discountedPrice: 4663,
      offer: "Hurry! Flat 5% Off",
      couponCode: "LABS10",
      is80DEligible: true,
    },
    {
      id: 18,
      title: "Master Full Body Health Checkup - Male (with cancer screening)",
      category: "full_body",
      reportsTime: "24 - 48 Hrs",
      testsCount: 88,
      tests: ["Creatinine - Serum", "Prostate Specific Antigen"],
      fasting: "10 - 12 Hrs",
      availableAt: "Home",
      originalPrice: 4699,
      discount: "51% OFF",
      discountedPrice: 2299,
      offer: "Hurry! Flat 5% Off",
      couponCode: "LABS10",
      is80DEligible: true,
    },
    {
      id: 19,
      title: "MediBuddy Diabetes Screening",
      category: "diabetes",
      reportsTime: "24 - 48 Hrs",
      testsCount: 54,
      tests: ["Glucose Fasting (FBS)", "Triglycerides - Serum"],
      fasting: "10 - 12 Hrs",
      availableAt: "Home",
      originalPrice: 2699,
      discount: "51% OFF",
      discountedPrice: 1299,
      offer: "Hurry! Flat 5% Off",
      couponCode: "LABS10",
      is80DEligible: true,
    },
    {
      id: 20,
      title: "Medibuddy Cardiac Health Package With ECG - Basic",
      category: "heart",
      reportsTime: "24 - 48 Hrs",
      testsCount: 52,
      tests: [
        "Complete Blood Count (CBC with P.Smear) - EDTA Whole Blood",
        "Glycosylated Hemoglobin (HBA1c) - EDTA Whole Blood",
      ],
      fasting: "10 - 12 Hrs",
      availableAt: "Home",
      originalPrice: 2199,
      discount: "50% OFF",
      discountedPrice: 1099,
      offer: "Hurry! Flat 5% Off",
      couponCode: "LABS10",
      is80DEligible: true,
    },
    {
      id: 21,
      title: "Medibuddy Cardiac Health Package With ECG - Comprehensive",
      category: "heart",
      reportsTime: "24 - 48 Hrs",
      testsCount: 58,
      tests: [
        "Complete Blood Count (CBC with P.Smear) - EDTA Whole Blood",
        "Glycosylated Hemoglobin (HBA1c) - EDTA Whole Blood",
      ],
      fasting: "10 - 12 Hrs",
      availableAt: "Home",
      originalPrice: 3999,
      discount: "50% OFF",
      discountedPrice: 1999,
      offer: "Hurry! Flat 5% Off",
      couponCode: "LABS10",
      is80DEligible: true,
    },
    {
      id: 22,
      title: "Master Full Body Health Checkup - Male (with cancer screening)",
      category: "cancer",
      reportsTime: "24 - 48 Hrs",
      testsCount: 88,
      tests: ["Creatinine - Serum", "Prostate Specific Antigen"],
      fasting: "10 - 12 Hrs",
      availableAt: "Home",
      originalPrice: 4699,
      discount: "51% OFF",
      discountedPrice: 2299,
      offer: "Hurry! Flat 5% Off",
      couponCode: "LABS10",
      is80DEligible: true,
    },
    {
      id: 23,
      title: "MediBuddy Basic Extended Health Checkup With Cancer Screening Male",
      category: "cancer",
      reportsTime: "24 - 48 Hrs",
      testsCount: 65,
      tests: ["Prostate Specific Antigen", "Bilirubin Profile"],
      fasting: "10 - 12 Hrs",
      availableAt: "Home",
      originalPrice: 2199,
      discount: "27% OFF",
      discountedPrice: 1599,
      offer: "Hurry! Flat 5% Off",
      couponCode: "LABS10",
      is80DEligible: true,
    },
    {
      id: 24,
      title: "Alcohol Impact Package",
      category: "alcohol",
      reportsTime: "24 - 48 Hrs",
      testsCount: 61,
      tests: [
        "Haemogram (CBC+ESR) - EDTA Whole Blood",
        "Kidney Function Test (KFT) - Serum",
      ],
      fasting: "10 - 12 Hrs",
      availableAt: "Home",
      originalPrice: 2999,
      discount: "56% OFF",
      discountedPrice: 1299,
      offer: "Hurry! Flat 5% Off",
      couponCode: "LABS10",
      is80DEligible: true,
    },
    {
      id: 25,
      title: "Smokers Health Checkup",
      category: "smoker",
      reportsTime: "24 - 48 Hrs",
      testsCount: 72,
      tests: [
        "Glycosylated Hemoglobin (HBA1c) - EDTA Whole Blood",
        "Haemogram (CBC+ESR) - EDTA Whole Blood",
      ],
      fasting: "6 - 8 Hrs",
      availableAt: "Home",
      originalPrice: 4999,
      discount: "52% OFF",
      discountedPrice: 2399,
      offer: "Hurry! Flat 5% Off",
      couponCode: "LABS10",
      is80DEligible: true,
    },
    {
      id: 26,
      title: "Comprehensive Full Body Checkup with Vitamin D & B12",
      category: "vitamin",
      reportsTime: "24 - 48 Hrs",
      testsCount: 85,
      tests: ["Vitamin D & B12", "Thyroid & Lipid profile"],
      fasting: "10 - 12 Hrs",
      availableAt: "Home",
      originalPrice: 4999,
      discount: "50% OFF",
      discountedPrice: 2499,
      offer: "Hurry! Flat 5% Off",
      couponCode: "LABS10",
      is80DEligible: true,
    },
    {
      id: 27,
      title: "MB Pack 32",
      category: "vitamin",
      reportsTime: "24 - 48 Hrs",
      testsCount: 50,
      tests: [
        "Complete Blood Count (CBC) - EDTA Whole Blood",
        "Complete Urine Examination (CUE) - Spot Urine",
      ],
      fasting: "10 - 12 Hrs",
      availableAt: "Home",
      originalPrice: 660,
      discount: "0% OFF",
      discountedPrice: 660,
      offer: "",
      couponCode: "",
      is80DEligible: false,
    },
    {
      id: 28,
      title: "Joint Pain Package",
      category: "joint",
      reportsTime: "24 - 48 Hrs",
      testsCount: 69,
      tests: [
        "Complete Blood Count (CBC with P.Smear) - EDTA Whole Blood",
        "Glycosylated Hemoglobin (HBA1c) - EDTA Whole Blood",
      ],
      fasting: "6 - 8 Hrs",
      availableAt: "Home",
      originalPrice: 2999,
      discount: "30% OFF",
      discountedPrice: 2099,
      offer: "Hurry! Flat 5% Off",
      couponCode: "LABS10",
      is80DEligible: true,
    },
    {
      id: 29,
      title: "Weight Management Package",
      category: "weight",
      reportsTime: "24 - 48 Hrs",
      testsCount: 49,
      tests: [
        "Complete Blood Count (CBC with P.Smear) - EDTA Whole Blood",
        "Glycosylated Hemoglobin (HBA1c) - EDTA Whole Blood",
      ],
      fasting: "10 - 12 Hrs",
      availableAt: "Home",
      originalPrice: 6499,
      discount: "53% OFF",
      discountedPrice: 2999,
      offer: "Hurry! Flat 5% Off",
      couponCode: "LABS10",
      is80DEligible: true,
    },
    {
      id: 30,
      title: "Women’s Staying Strong Health Checkup",
      category: "women_health",
      reportsTime: "24 - 48 Hrs",
      testsCount: 92,
      tests: [
        "Complete Blood Count (CBC) - EDTA Whole Blood",
        "Complete Urine Examination (CUE) - Spot Urine",
      ],
      fasting: "10 - 12 Hrs",
      availableAt: "Home",
      originalPrice: 6999,
      discount: "50% OFF",
      discountedPrice: 3499,
      offer: "Hurry! Flat 5% Off",
      couponCode: "LABS10",
      is80DEligible: true,
    },
    {
      id: 31,
      title: "Women’s Golden Gift Health Checkup",
      category: "women_health",
      reportsTime: "24 - 48 Hrs",
      testsCount: 103,
      tests: [
        "Complete Blood Count (CBC with P.Smear) - EDTA Whole Blood",
        "Complete Urine Examination (CUE) - Spot Urine",
      ],
      fasting: "10 - 12 Hrs",
      availableAt: "Home",
      originalPrice: 9499,
      discount: "50% OFF",
      discountedPrice: 4699,
      offer: "Hurry! Flat 5% Off",
      couponCode: "LABS10",
      is80DEligible: true,
    },
    {
      id: 32,
      title: "Women's Primary Prevention Health Checkup",
      category: "women_health",
      reportsTime: "24 - 48 Hrs",
      testsCount: 88,
      tests: ["Iron Urea Uric Acid - Serum", "Vitamin D & B12"],
      fasting: "10 - 12 Hrs",
      availableAt: "Home",
      originalPrice: 4599,
      discount: "50% OFF",
      discountedPrice: 2299,
      offer: "Hurry! Flat 5% Off",
      couponCode: "LABS10",
      is80DEligible: true,
    },
    {
      id: 33,
      title: "Hormone Profile - Female",
      category: "women_health",
      reportsTime: "24 - 48 Hrs",
      testsCount: 9,
      tests: [
        "Thyroid Profile (T3,T4 & TSH) - Serum",
        "Anti Mullerian Hormone (AMH) - Serum",
      ],
      fasting: "6 - 8 Hrs",
      availableAt: "Home",
      originalPrice: 3999,
      discount: "50% OFF",
      discountedPrice: 1999,
      offer: "Hurry! Flat 5% Off",
      couponCode: "LABS10",
      is80DEligible: true,
    },
    {
      id: 34,
      title: "MediBuddy Young Male Health Checkup",
      category: "men_health",
      reportsTime: "24 - 48 Hrs",
      testsCount: 92,
      tests: [
        "Complete Blood Count (CBC) - EDTA Whole Blood",
        "Complete Urine Examination (CUE) - Spot Urine",
      ],
      fasting: "10 - 12 Hrs",
      availableAt: "Home",
      originalPrice: 6999,
      discount: "50% OFF",
      discountedPrice: 3499,
      offer: "Hurry! Flat 5% Off",
      couponCode: "LABS10",
      is80DEligible: true,
    },
    {
      id: 35,
      title: "MediBuddy Elderly Male Health Checkup",
      category: "men_health",
      reportsTime: "24 - 48 Hrs",
      testsCount: 107,
      tests: [
        "Complete Blood Count (CBC with P.Smear) - EDTA Whole Blood",
        "Complete Urine Examination (CUE) - Spot Urine",
      ],
      fasting: "10 - 12 Hrs",
      availableAt: "Home",
      originalPrice: 9499,
      discount: "50% OFF",
      discountedPrice: 4699,
      offer: "Hurry! Flat 5% Off",
      couponCode: "LABS10",
      is80DEligible: true,
    },
    {
      id: 36,
      title: "STD Panel",
      category: "sexual_wellness",
      reportsTime: "24 - 48 Hrs",
      testsCount: 5,
      tests: [
        "Chlamydia Antibodies IgG - Serum",
        "Herpes Simplex Virus 1 & 2 IgG - Serum",
      ],
      fasting: "6 - 8 Hrs",
      availableAt: "Home, Center",
      originalPrice: 5299,
      discount: "49% OFF",
      discountedPrice: 2699,
      offer: "Hurry! Flat 5% Off",
      couponCode: "LABS10",
      is80DEligible: true,
    },
    {
      id: 37,
      title: "Hair Care Package",
      category: "hair_care",
      reportsTime: "24 - 48 Hrs",
      testsCount: 35,
      tests: ["Haemogram (CBC+ESR)", "Glycosylated Haemoglobin"],
      fasting: "6 - 8 Hrs",
      availableAt: "Home",
      originalPrice: 2999,
      discount: "50% OFF",
      discountedPrice: 1499,
      offer: "Hurry! Flat 5% Off",
      couponCode: "LABS10",
      is80DEligible: true,
    },
    {
      id: 38,
      title: "Stress Level Package",
      category: "stress",
      reportsTime: "24 - 48 Hrs",
      testsCount: 27,
      tests: ["Haemogram (CBC+ESR)", "Cortisol - Serum"],
      fasting: "10 - 12 Hrs",
      availableAt: "Home",
      originalPrice: 1499,
      discount: "40% OFF",
      discountedPrice: 899,
      offer: "Hurry! Flat 5% Off",
      couponCode: "LABS10",
      is80DEligible: true,
    },
    {
      id: 39,
      title: "MediBuddy Full body Health Checkup",
      category: "liver",
      reportsTime: "24 - 48 Hrs",
      testsCount: 81,
      tests: ["Thyroid & Lipid Profile", "Kidney & Liver function tests"],
      fasting: "10 - 12 Hrs",
      availableAt: "Home",
      originalPrice: 2999,
      discount: "53% OFF",
      discountedPrice: 1399,
      offer: "Hurry! Flat 5% Off",
      couponCode: "LABS10",
      is80DEligible: true,
    },
    {
      id: 40,
      title: "Women’s Golden Gift Health Checkup",
      category: "senior_citizen",
      reportsTime: "24 - 48 Hrs",
      testsCount: 103,
      tests: [
        "Complete Blood Count (CBC with P.Smear) - EDTA Whole Blood",
        "Complete Urine Examination (CUE) - Spot Urine",
      ],
      fasting: "10 - 12 Hrs",
      availableAt: "Home",
      originalPrice: 9499,
      discount: "50% OFF",
      discountedPrice: 4699,
      offer: "Hurry! Flat 5% Off",
      couponCode: "LABS10",
      is80DEligible: true,
    },
    {
      id: 41,
      title: "MediBuddy Elderly Male Health Checkup",
      category: "senior_citizen",
      reportsTime: "24 - 48 Hrs",
      testsCount: 107,
      tests: [
        "Complete Blood Count (CBC with P.Smear) - EDTA Whole Blood",
        "Complete Urine Examination (CUE) - Spot Urine",
      ],
      fasting: "10 - 12 Hrs",
      availableAt: "Home",
      originalPrice: 9499,
      discount: "50% OFF",
      discountedPrice: 4699,
      offer: "Hurry! Flat 5% Off",
      couponCode: "LABS10",
      is80DEligible: true,
    },
    {
      id: 42,
      title: "MediBuddy Kid's Exclusive Health Checkup",
      category: "kids",
      reportsTime: "24 - 48 Hrs",
      testsCount: 58,
      tests: [
        "Complete Blood Count (CBC) - EDTA Whole Blood",
        "Complete Urine Examination (CUE) - Spot Urine",
      ],
      fasting: "10 - 12 Hrs",
      availableAt: "Home",
      originalPrice: 3999,
      discount: "50% OFF",
      discountedPrice: 1999,
      offer: "Hurry! Flat 5% Off",
      couponCode: "LABS10",
      is80DEligible: true,
    },
    {
      id: 43,
      title: "MediBuddy Kid's Basic Health Check-up",
      category: "kids",
      reportsTime: "24 - 48 Hrs",
      testsCount: 30,
      tests: [
        "Blood Grouping & Rh Type - EDTA Whole Blood",
        "Complete Blood Count (CBC with P.Smear) - EDTA Whole Blood",
      ],
      fasting: "10 - 12 Hrs",
      availableAt: "Home",
      originalPrice: 1599,
      discount: "43% OFF",
      discountedPrice: 899,
      offer: "Hurry! Flat 5% Off",
      couponCode: "LABS10",
      is80DEligible: true,
    },
    {
      id: 44,
      title: "Medibuddy Swift Health Checkup",
      category: "popular",
      reportsTime: "24 - 48 Hrs",
      testsCount: 44,
      tests: [
        "Complete Blood Count (CBC) - EDTA Whole Blood",
        "Complete Urine Examination (CUE) - Spot Urine",
      ],
      fasting: "6 - 8 Hrs",
      availableAt: "Home",
      originalPrice: 1999,
      discount: "50% OFF",
      discountedPrice: 999,
      offer: "Hurry! Flat 5% Off",
      couponCode: "LABS10",
      is80DEligible: true,
    },
    {
      id: 45,
      title: "Women's Primary Prevention Health Checkup",
      category: "popular",
      reportsTime: "24 - 48 Hrs",
      testsCount: 88,
      tests: ["Iron Urea Uric Acid - Serum", "Vitamin D & B12"],
      fasting: "10 - 12 Hrs",
      availableAt: "Home",
      originalPrice: 4599,
      discount: "50% OFF",
      discountedPrice: 2299,
      offer: "Hurry! Flat 5% Off",
      couponCode: "LABS10",
      is80DEligible: true,
    },
    {
      id: 46,
      title: "MB Pack 1",
      category: "popular",
      reportsTime: "24 - 48 Hrs",
      testsCount: 46,
      tests: ["2D Echo/Doppler Study", "Ultrasound & ECG"],
      fasting: "10 - 12 Hrs",
      availableAt: "Center",
      originalPrice: 3354,
      discount: "23% OFF",
      discountedPrice: 2580,
      offer: "Hurry! Flat 5% Off",
      couponCode: "LABS10",
      is80DEligible: true,
      includes: [
        {
          id: 1,
          name: "Radiology",
          icon: "https://www.medibuddy.in/assets/icons/corpLabs/radiology-icon.svg",
        },
        {
          id: 2,
          name: "2 Consultations",
          icon: "https://www.medibuddy.in/assets/icons/doctor.svg",
        },
      ],
    },
    {
      id: 47,
      title: "MediBuddy Advance Health Checkup",
      category: "popular",
      reportsTime: "24 - 48 Hrs",
      testsCount: 82,
      tests: ["Calcium Phosphorus - Serum", "Glycosylated Hemoglobin"],
      fasting: "6 - 8 Hrs",
      availableAt: "Home",
      originalPrice: 3499,
      discount: "48% OFF",
      discountedPrice: 1799,
      offer: "Hurry! Flat 5% Off",
      couponCode: "LABS10",
      is80DEligible: true,
    },
    {
      id: 48,
      title: "MediBuddy Diabetes Screening",
      category: "popular",
      reportsTime: "24 - 48 Hrs",
      testsCount: 54,
      tests: ["Glucose Fasting (FBS)", "Triglycerides - Serum"],
      fasting: "10 - 12 Hrs",
      availableAt: "Home",
      originalPrice: 2699,
      discount: "51% OFF",
      discountedPrice: 1299,
      offer: "Hurry! Flat 5% Off",
      couponCode: "LABS10",
      is80DEligible: true,
    },
    {
      id: 49,
      title: "MediBuddy Young Male Health Checkup",
      category: "popular",
      reportsTime: "24 - 48 Hrs",
      testsCount: 92,
      tests: [
        "Complete Blood Count (CBC) - EDTA Whole Blood",
        "Complete Urine Examination (CUE) - Spot Urine",
      ],
      fasting: "10 - 12 Hrs",
      availableAt: "Home",
      originalPrice: 6999,
      discount: "50% OFF",
      discountedPrice: 3499,
      offer: "Hurry! Flat 5% Off",
      couponCode: "LABS10",
      is80DEligible: true,
    },
    {
      id: 50,
      title: "MediBuddy Prime Comprehensive Health Checkup",
      category: "popular",
      reportsTime: "24 - 48 Hrs",
      testsCount: 85,
      tests: [
        "Complete Blood Count (CBC) - EDTA Whole Blood",
        "Complete Urine Examination (CUE) - Spot Urine",
      ],
      fasting: "10 - 12 Hrs",
      availableAt: "Home",
      originalPrice: 4599,
      discount: "50% OFF",
      discountedPrice: 2299,
      offer: "Hurry! Flat 5% Off",
      couponCode: "LABS10",
      is80DEligible: true,
    },
    {
      id: 51,
      title: "Medibuddy Smart Health Checkup",
      category: "popular",
      reportsTime: "24 - 48 Hrs",
      testsCount: 44,
      tests: [
        "Complete Blood Count (CBC) - EDTA Whole Blood",
        "Complete Urine Examination (CUE) - Spot Urine",
      ],
      fasting: "6 - 8 Hrs",
      availableAt: "Home",
      originalPrice: 1999,
      discount: "35% OFF",
      discountedPrice: 1299,
      offer: "Hurry! Flat 5% Off",
      couponCode: "LABS10",
      is80DEligible: true,
    },
    {
      id: 52,
      title: "Master Full Body Health Checkup - Male (with cancer screening)",
      category: "popular",
      reportsTime: "24 - 48 Hrs",
      testsCount: 88,
      tests: ["Creatinine - Serum", "Prostate Specific Antigen"],
      fasting: "10 - 12 Hrs",
      availableAt: "Home",
      originalPrice: 4699,
      discount: "51% OFF",
      discountedPrice: 2299,
      offer: "Hurry! Flat 5% Off",
      couponCode: "LABS10",
      is80DEligible: true,
    },
    {
      id: 53,
      title: "MediBuddy Basic Extended Health Check-up",
      category: "popular",
      reportsTime: "24 - 48 Hrs",
      testsCount: 60,
      tests: [
        "Complete Blood Count (CBC) - EDTA Whole Blood",
        "Complete Urine Examination (CUE) - Spot Urine",
      ],
      fasting: "10 - 12 Hrs",
      availableAt: "Home",
      originalPrice: 2699,
      discount: "37% OFF",
      discountedPrice: 1699,
      offer: "Hurry! Flat 5% Off",
      couponCode: "LABS10",
      is80DEligible: true,
    },
    {
      id: 54,
      title: "MediBuddy Full Body Health Checkup",
      category: "popular",
      reportsTime: "24 - 48 Hrs",
      testsCount: 81,
      tests: [
        "Complete Blood Count (CBC) - EDTA Whole Blood",
        "Complete Urine Examination (CUE) - Spot Urine",
      ],
      fasting: "10 - 12 Hrs",
      availableAt: "Home, Center",
      originalPrice: 2399,
      discount: "8% OFF",
      discountedPrice: 2199,
      offer: "Hurry! Flat 5% Off",
      couponCode: "LABS10",
      is80DEligible: true,
    },
    {
      id: 55,
      title: "Medibuddy Prime Health Checkup",
      category: "popular",
      reportsTime: "24 - 48 Hrs",
      testsCount: 84,
      tests: [
        "Complete Blood Count (CBC) - EDTA Whole Blood",
        "Complete Urine Examination (CUE) - Spot Urine",
      ],
      fasting: "10 - 12 Hrs",
      availableAt: "Home",
      originalPrice: 3499,
      discount: "5% OFF",
      discountedPrice: 3299,
      offer: "Hurry! Flat 5% Off",
      couponCode: "LABS10",
      is80DEligible: true,
    },
    {
      id: 56,
      title: "MB Pack 1",
      category: "center_visit",
      reportsTime: "24 - 48 Hrs",
      testsCount: 46,
      tests: ["2D Echo/Doppler Study", "Ultrasound & ECG"],
      fasting: "10 - 12 Hrs",
      availableAt: "Center",
      originalPrice: 3354,
      discount: "23% OFF",
      discountedPrice: 2580,
      offer: "Hurry! Flat 5% Off",
      couponCode: "LABS10",
      is80DEligible: true,
      includes: [
        {
          id: 1,
          name: "Radiology",
          icon: "https://www.medibuddy.in/assets/icons/corpLabs/radiology-icon.svg",
        },
        {
          id: 2,
          name: "2 Consultations",
          icon: "https://www.medibuddy.in/assets/icons/doctor.svg",
        },
      ],
    },
    {
      id: 57,
      title: "MB Pack 2",
      category: "center_visit",
      reportsTime: "24 - 48 Hrs",
      testsCount: 42,
      tests: ["X-Ray Chest", "Pap Smear - Liquid Based"],
      fasting: "10 - 12 Hrs",
      availableAt: "Center",
      originalPrice: 2366,
      discount: "23% OFF",
      discountedPrice: 1820,
      includes: [
        {
          id: 1,
          name: "Radiology",
          icon: "https://www.medibuddy.in/assets/icons/corpLabs/radiology-icon.svg",
        },
        {
          id: 2,
          name: "3 Consultations",
          icon: "https://www.medibuddy.in/assets/icons/doctor.svg",
        },
      ],
    },
    {
      id: 58,
      title: "MB Pack 3",
      category: "center_visit",
      reportsTime: "24 - 48 Hrs",
      testsCount: 44,
      tests: ["Ultrasound (Abdomen)", "Electrocardiogram (ECG)"],
      fasting: "10 - 12 Hrs",
      availableAt: "Center",
      originalPrice: 2496,
      discount: "23% OFF",
      discountedPrice: 1920,
      includes: [
        {
          id: 1,
          name: "Radiology",
          icon: "https://www.medibuddy.in/assets/icons/corpLabs/radiology-icon.svg",
        },
        {
          id: 2,
          name: "1 Consultation",
          icon: "https://www.medibuddy.in/assets/icons/doctor.svg",
        },
      ],
    },
    {
      id: 59,
      title: "MB Pack 11",
      category: "center_visit",
      reportsTime: "24 - 48 Hrs",
      testsCount: 37,
      tests: ["X-Ray Chest", "Electrocardiogram (ECG)"],
      fasting: "10 - 12 Hrs",
      availableAt: "Center",
      originalPrice: 1365,
      discount: "23% OFF",
      discountedPrice: 1050,
      includes: [
        {
          id: 1,
          name: "Radiology",
          icon: "https://www.medibuddy.in/assets/icons/corpLabs/radiology-icon.svg",
        },
        {
          id: 2,
          name: "2 Consultations",
          icon: "https://www.medibuddy.in/assets/icons/doctor.svg",
        },
      ],
    },
    {
      id: 60,
      title: "MB Pack 12",
      category: "center_visit",
      reportsTime: "24 - 48 Hrs",
      testsCount: 47,
      tests: ["Ultrasound & ECG", "Creatinine - Serum"],
      fasting: "10 - 12 Hrs",
      availableAt: "Center",
      originalPrice: 2990,
      discount: "23% OFF",
      discountedPrice: 2300,
      offer: "Hurry! Flat 5% Off",
      couponCode: "LABS10",
      includes: [
        {
          id: 1,
          name: "Radiology",
          icon: "https://www.medibuddy.in/assets/icons/corpLabs/radiology-icon.svg",
        },
        {
          id: 2,
          name: "3 Consultations",
          icon: "https://www.medibuddy.in/assets/icons/doctor.svg",
        },
      ],
    },
    {
      id: 61,
      title: "MB Pack 13",
      category: "center_visit",
      reportsTime: "24 - 48 Hrs",
      testsCount: 34,
      tests: [
        "Complete Blood Count (CBC) - EDTA Whole Blood",
        "2D Echo/Doppler Study",
      ],
      fasting: "10 - 12 Hrs",
      availableAt: "Center",
      originalPrice: 2899,
      discount: "23% OFF",
      discountedPrice: 2230,
      includes: [
        {
          id: 1,
          name: "Radiology",
          icon: "https://www.medibuddy.in/assets/icons/corpLabs/radiology-icon.svg",
        },
        {
          id: 2,
          name: "3 Consultations",
          icon: "https://www.medibuddy.in/assets/icons/doctor.svg",
        },
      ],
    },
    {
      id: 62,
      title: "MB Pack 14",
      category: "center_visit",
      reportsTime: "24 - 48 Hrs",
      testsCount: 50,
      tests: ["Thyroid Profile", "ECG & X-Ray Chest"],
      fasting: "10 - 12 Hrs",
      availableAt: "Center",
      originalPrice: 2340,
      discount: "23% OFF",
      discountedPrice: 1800,
      offer: "Hurry! Flat 5% Off",
      couponCode: "LABS10",
      includes: [
        {
          id: 1,
          name: "Radiology",
          icon: "https://www.medibuddy.in/assets/icons/corpLabs/radiology-icon.svg",
        },
        {
          id: 2,
          name: "1 Consultation",
          icon: "https://www.medibuddy.in/assets/icons/doctor.svg",
        },
      ],
    },
    {
      id: 63,
      title: "MB Pack 15",
      category: "center_visit",
      reportsTime: "24 - 48 Hrs",
      testsCount: 45,
      tests: [
        "Bilirubin Profile (Total, Direct & Indirect) - Serum",
        "Complete Blood Count (CBC) - EDTA Whole Blood",
      ],
      fasting: "10 - 12 Hrs",
      availableAt: "Center",
      originalPrice: 2470,
      discount: "23% OFF",
      discountedPrice: 1900,
      includes: [
        {
          id: 1,
          name: "Radiology",
          icon: "https://www.medibuddy.in/assets/icons/corpLabs/radiology-icon.svg",
        },
        {
          id: 2,
          name: "3 Consultations",
          icon: "https://www.medibuddy.in/assets/icons/doctor.svg",
        },
      ],
    },
    {
      id: 64,
      title: "MB Pack 16",
      category: "center_visit",
      reportsTime: "24 - 48 Hrs",
      testsCount: 47,
      tests: [
        "Bilirubin Profile (Total, Direct & Indirect) - Serum",
        "Complete Blood Count (CBC) - EDTA Whole Blood",
      ],
      fasting: "10 - 12 Hrs",
      availableAt: "Center",
      originalPrice: 3250,
      discount: "23% OFF",
      discountedPrice: 2500,
      includes: [
        {
          id: 1,
          name: "Radiology",
          icon: "https://www.medibuddy.in/assets/icons/corpLabs/radiology-icon.svg",
        },
        {
          id: 2,
          name: "1 Consultation",
          icon: "https://www.medibuddy.in/assets/icons/doctor.svg",
        },
      ],
    },
    {
      id: 65,
      title: "MB Pack 17",
      category: "center_visit",
      reportsTime: "24 - 48 Hrs",
      testsCount: 43,
      tests: [
        "Bilirubin Profile (Total, Direct & Indirect) - Serum",
        "Complete Blood Count (CBC) - EDTA Whole Blood",
      ],
      fasting: "10 - 12 Hrs",
      availableAt: "Center",
      originalPrice: 3640,
      discount: "23% OFF",
      discountedPrice: 2800,
      offer: "Hurry! Flat 5% Off",
      couponCode: "LABS10",
      includes: [
        {
          id: 1,
          name: "Radiology",
          icon: "https://www.medibuddy.in/assets/icons/corpLabs/radiology-icon.svg",
        },
        {
          id: 2,
          name: "3 Consultations",
          icon: "https://www.medibuddy.in/assets/icons/doctor.svg",
        },
      ],
    },
    {
      id: 66,
      title: "MB Pack 21",
      category: "center_visit",
      reportsTime: "24 - 48 Hrs",
      testsCount: 59,
      tests: [
        "Bilirubin Profile (Total, Direct & Indirect) - Serum",
        "Blood Grouping & Rh Type - EDTA Whole Blood",
      ],
      fasting: "10 - 12 Hrs",
      availableAt: "Center",
      originalPrice: 5876,
      discount: "23% OFF",
      discountedPrice: 4520,
      includes: [
        {
          id: 1,
          name: "Radiology",
          icon: "https://www.medibuddy.in/assets/icons/corpLabs/radiology-icon.svg",
        },
        {
          id: 2,
          name: "3 Consultations",
          icon: "https://www.medibuddy.in/assets/icons/doctor.svg",
        },
      ],
    },
    {
      id: 67,
      title: "MB Pack 18",
      category: "center_visit",
      reportsTime: "24 - 48 Hrs",
      testsCount: 61,
      tests: [
        "Bilirubin Profile (Total, Direct & Indirect) - Serum",
        "Complete Blood Count (CBC) - EDTA Whole Blood",
      ],
      fasting: "10 - 12 Hrs",
      availableAt: "Center",
      originalPrice: 5330,
      discount: "23% OFF",
      discountedPrice: 4100,
      offer: "Hurry! Flat 5% Off",
      couponCode: "LABS10",
      includes: [
        {
          id: 1,
          name: "Radiology",
          icon: "https://www.medibuddy.in/assets/icons/corpLabs/radiology-icon.svg",
        },
        {
          id: 2,
          name: "4 Consultations",
          icon: "https://www.medibuddy.in/assets/icons/doctor.svg",
        },
      ],
    },
    {
      id: 68,
      title: "MB Pack 19",
      category: "center_visit",
      reportsTime: "24 - 48 Hrs",
      testsCount: 51,
      tests: [
        "Bilirubin Profile (Total, Direct & Indirect) - Serum",
        "Blood Grouping & Rh Type - EDTA Whole Blood",
      ],
      fasting: "10 - 12 Hrs",
      availableAt: "Center",
      originalPrice: 4680,
      discount: "23% OFF",
      discountedPrice: 3600,
      includes: [
        {
          id: 1,
          name: "Radiology",
          icon: "https://www.medibuddy.in/assets/icons/corpLabs/radiology-icon.svg",
        },
        {
          id: 2,
          name: "5 Consultations",
          icon: "https://www.medibuddy.in/assets/icons/doctor.svg",
        },
      ],
    },
    {
      id: 69,
      title: "MB Pack 20",
      category: "center_visit",
      reportsTime: "24 - 48 Hrs",
      testsCount: 56,
      tests: [
        "Bilirubin Profile (Total, Direct & Indirect) - Serum",
        "Complete Blood Count (CBC) - EDTA Whole Blood",
      ],
      fasting: "10 - 12 Hrs",
      availableAt: "Center",
      originalPrice: 4290,
      discount: "23% OFF",
      discountedPrice: 3300,
      offer: "Hurry! Flat 5% Off",
      couponCode: "LABS10",
      includes: [
        {
          id: 1,
          name: "Radiology",
          icon: "https://www.medibuddy.in/assets/icons/corpLabs/radiology-icon.svg",
        },
        {
          id: 2,
          name: "4 Consultations",
          icon: "https://www.medibuddy.in/assets/icons/doctor.svg",
        },
      ],
    },
    {
      id: 70,
      title: "MB Pack 22",
      category: "center_visit",
      reportsTime: "24 - 48 Hrs",
      testsCount: 62,
      tests: [
        "Bilirubin Profile (Total, Direct & Indirect) - Serum",
        "Complete Blood Count (CBC) - EDTA Whole Blood",
      ],
      fasting: "10 - 12 Hrs",
      availableAt: "Center",
      originalPrice: 6630,
      discount: "23% OFF",
      discountedPrice: 5100,
      includes: [
        {
          id: 1,
          name: "Radiology",
          icon: "https://www.medibuddy.in/assets/icons/corpLabs/radiology-icon.svg",
        },
        {
          id: 2,
          name: "5 Consultations",
          icon: "https://www.medibuddy.in/assets/icons/doctor.svg",
        },
      ],
    },
  ];